config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :klasses, except: [:edit, :new] do
        resources :sections, except: [:edit, :new] do
          resources :students, except: [:edit, :new]
        end
      end
    end
    namespace :v2 do
      resources :klasses, except: [:edit, :new]
    end
    namespace :v3 do
      resources :klasses, except: [:edit, :new]
    end
  end

  resources :klasses do
    resources :sections do
      resources  :students
      resources  :attendance_registries
    end
  end

  resources :exams, only: [:index, :new, :create]

  root 'klasses#index'

end

app/models/student.rb
# == Schema Information
#
# Table name: students
#
#  id           :integer          not null, primary key
#  section_id   :integer
#  house_id     :integer
#  roll_number  :integer
#  name         :string
#  fathers_name :string
#  gender       :integer
#  email        :string
#  dob          :date
#  phone        :string
#  address      :text
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Student < ActiveRecord::Base
  module Gender
    MALE = {code: 1, label: "Male"}
    FEMALE = {code: 2, label: "Female"}

    def self.label(code)
      if code == MALE[:code]
        return MALE[:label]
      else
        return FEMALE[:label]
      end
    end

    def self.all
      [MALE, FEMALE].collect{|hsh| OpenStruct.new(hsh)}
    end
  end

  belongs_to :section
  belongs_to :house
  
  has_one :exam
end

app/controllers/api/v1/students_controller.rb
module Api
  module V1
    class StudentsController < ApplicationController

      before_action :fetch_klass_section

      before_action :fetch_student, only: [:show, :update, :destroy]


      def index
        @students = @section.students
      end

      def show
      end

      def create
        @student = @section.students.new(student_params)

        if @student.save
          head :created, location: api_v1_klass_section_students_url(@klass, @section)
        else
          head :bad_request
        end
      end

      # def create
      #   @student = @section.students.new
      #   @student = @klass.students.new
      #   @student.roll_number = params[:roll_number]
      #   @student.name = params[:name]
      #   @student.fathers_name = params[:fathers_name]
      #   @student.gender = params[:gender]
      #   @student.email = params[:email]
      #   @student.dob = params[:dob]
      #   @student.phone = params[:phone]
      #   @student.address = params[:address]
      #   @student.house_id = params[:house_id]
      #   @student.section_id = params[:section_id]
      #
      #   if @student.save
      #     head :created, location: api_v1_klass_section_students_url(@klass, @section)
      #   else
      #     head :bad_request
      #   end
      # end

      # def update
      #   if @student.update_attributes(student_params)
      #     head :ok, location: api_v1_klass_section_student_url(@klass, @section,@student)
      #   else
      #     head :bad_request
      #   end
      # end

      # def update
      #   @student.roll_number = params[:roll_number]
      #   @student.name = params[:name]
      #   @student.fathers_name = params[:fathers_name]
      #   @student.gender = params[:gender]
      #   @student.email = params[:email]
      #   @student.dob = params[:dob]
      #   @student.phone = params[:phone]
      #   @student.address = params[:address]
      #   @student.house_id = params[:house_id]
      #   @student.section_id = params[:section_id]
      #
      #   if @student.save
      #     head :created, location: api_v1_klass_section_students_url(@klass, @section)
      #   else
      #     head :bad_request
      #   end
      # end




      def update
        @student.name = params[:name] || @student.name
        @student.roll_number = params[:roll_number] || @student.roll_number
        @student.fathers_name = params[:fathers_name] || @student.fathers_name
        @student.gender = params[:gender] || @student.gender
        @student.email = params[:email] || @student.email
        @student.dob = params[:dob] || @student.dob
        @student.phone = params[:phone] || @student.phone
        @student.address = params[:address] || @student.address
        @student.house_id = params[:house_id] || @student.house_id
        @student.section_id = params[:section_id] || @student.section_id
        if @student.save
          head :ok, location: api_v1_klass_section_student_url(@klass, @section, @student)
        else
          head :bad_request
        end
      end

      def destroy
        if params[:name] == @student.name
          @student.destroy
          head :ok
        else
          head :bad_request
        end
      end

    private
      def fetch_klass_section
        @klass = Klass.find(params[:klass_id])
        @section = @klass.sections.find(params[:section_id])
      end

      def fetch_student
        @student = @section.students.find(params[:id])
      end

      def student_params
        params.require(:student).permit(:name, :roll_number, :fathers_name, :gender, :email, :address, :phone, :dob, :house_id)
      end
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  before_action :fetch_klass_section

  def index
    @students = @section.students.includes(:house)
  end

  def new
    @student = @section.students.new
  end

  def create
    @student = @section.students.new(student_params)
    @save_success = @student.save
  end

  def show
    @student = @section.students.find(params[:id])
  end

  def edit
    @student = @section.students.find(params[:id])
  end

  def update
    @student = @section.students.find(params[:id])
    @save_success = @student.update_attributes(student_params)

  end
private
  def fetch_klass_section
    @klass = Klass.find(params[:klass_id])
    @section = @klass.sections.find(params[:section_id])
  end

  def student_params
    params.require(:student).permit(:roll_number, :name, :fathers_name, :gender, :email, :address, :phone, :dob, :house_id)
  end
end

app/helpers/students_helper.rb
module StudentsHelper
  COLOR_TO_CLASS = {
    "Yellow" => "warning",
    "Red" => "danger",
    "Blue" => "primary",
    "Green" => "success",
  }


  def student_house_label_class(student)
    house_name = student.house.name

    return COLOR_TO_CLASS[house_name]
  end

  # Sample argument:
  #   {"Yellow": 3, "Red": 4, "Blue": 6, "Green": 7}

  def house_counts_tag(hsh)
    str = ""
    hsh.each do |house_name, house_count|
      str += content_tag(:span, house_count, class: "pull-right label label-#{COLOR_TO_CLASS[house_name]}")
    end

    raw(str)
  end
end

app/views/students/_form.html.erb
<div class="modal fade" id="new_student" tabindex="-1" role="dialog" aria-labelledby="newStudent">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><%= @student.new_record? ? "Add a new Student" : "Update #{@student.name} Details" %></h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@klass, @section, @student], remote: true, html: { id: "new-student-form", class: "form-horizontal"}, wrapper: :horizontal_form do |f| %>
        <%= f.input :name %>
        <%= f.input :fathers_name %>
        <%= f.input :gender,include_blank: false, collection: Student::Gender.all, label_method: :label, value_method: :code %>
        <%= f.input :house_id, collection: House.all, include_blank: false, label_method: :name, value_method: :id %>
        <%= f.input :email %>
        <%= f.input :dob, as: :date, html5: true %>
        <%= f.input :phone %>
        <%= f.input :address %>
          <%= f.submit (@student.new_record? ? "Add Student" : "Update Details") , class:"btn btn-primary col-sm-offset-3"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/students/_student.html.erb
<%= link_to(klass_section_student_path(@klass, @section, student),
            class: "list-group-item student-item",
            id: dom_id(student), data: {toggle: "tooltip", placement: "right" }, title: "click for Student details!",
            remote: true) do
            content_tag(:span, raw("&nbsp"), class: "pull-right label label-#{student_house_label_class(student)}") +
            content_tag(:b, student.roll_number) + " " + student.name
          end
%>

app/views/students/_student_details.html.erb
<%= content_tag(:span, raw("&nbsp"), class: "pull-right label label-#{student_house_label_class(student)}")  %>
<dl class="dl-horizontal">
  <% [:roll_number, :name, :fathers_name, :email, :gender, :dob, :phone, :address].each do |property| %>
  <dt><%= property.to_s.gsub("_"," ").capitalize %></dt>
  <dd>
    <% if property == :gender %>
      <%= Student::Gender.label(student.gender) %>
    <% elsif property == :dob %>
      <%= student.dob.strftime("%B %-d, %Y") %>
    <% else %>
      <%= student.send(property) %>
    <% end %>
  </dd>
  <% end %>
</dl>

<%= link_to "Show Marks", exams_path(student_id: student.id),id: "student_marks_link", class: "pull-right btn btn-primary", remote: true %>

app/views/students/create.js.erb
$('#new_student').modal('hide')
<% if @save_success %>
  $("#students-list").append("<%= j render(@student) %>");

  $("form#new-student-form")[0].reset();
  // reset is defined on dom ele but not on jquery so [0] is added
<% end %>

app/views/students/edit.js.erb
$("#new_student").remove();
$("body").append("<%= j render(partial: "students/form") %>")
$('#new_student').modal('show')

app/views/students/index.js.erb
StudentDBUtils.show("#students");
$("#students-list").html('<%= j render(@students) %>');
$("#students .panel-heading a#add-student-trigger").attr('href', '<%= new_klass_section_student_path(@klass, @section) %>')
$("#students .panel-heading a#take-attendence-trigger").attr('href', '<%= new_klass_section_attendance_registry_path(@klass, @section) %>');
StudentDBUtils.hide("#student-details");
$("a.section-item").removeClass("active");
$("a#<%= dom_id(@section) %>").addClass("active");
StudentDBUtils.hide("#attendance");

app/views/students/new.js.erb
$("#new_student").remove();
$("body").append("<%= j render(partial: "students/form") %>")
$('#new_student').modal('show')

app/views/students/show.js.erb
StudentDBUtils.show("#student-details");
$("#student-details .panel-body").html('<%= j render(partial: "students/student_details",locals: {student: @student}) %>');
$("#student-details .panel-heading a").attr('href', '<%= edit_klass_section_student_path(@klass, @section, @student) %>');
$("a.student-item").removeClass("active");
$("a#<%= dom_id(@student) %>").addClass("active");

app/views/students/update.js.erb
$('#new_student').modal('hide')
<% if @save_success %>
  $("#student-details .panel-body").html('<%= j render(partial: "students/student_details",locals: {student: @student}) %>');
<% end %>