config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :klasses, except: [:edit, :new] do
        resources :sections, except: [:edit, :new] do
          resources :students, except: [:edit, :new]
        end
      end
    end
    namespace :v2 do
      resources :klasses, except: [:edit, :new]
    end
    namespace :v3 do
      resources :klasses, except: [:edit, :new]
    end
  end

  resources :klasses do
    resources :sections do
      resources  :students
      resources  :attendance_registries
    end
  end

  resources :exams, only: [:index, :new, :create]

  root 'klasses#index'

end

app/models/section.rb
# == Schema Information
#
# Table name: sections
#
#  id         :integer          not null, primary key
#  name       :string
#  klass_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Section < ActiveRecord::Base
  belongs_to :klass

  has_many :students, dependent: :destroy
  has_many :attendance_registries, dependent: :destroy

  def houses_count
    {
      "Red"    =>    red_count,
      "Yellow" => yellow_count,
      "Blue"   =>   blue_count,
      "Green"  =>  green_count,
    }
  end


private
  def red_count
    students.select{ |st| st.house.name == "Red"}.count
  end

  def yellow_count
    students.select{ |st| st.house.name == "Yellow"}.count
  end

  def blue_count
    students.select{ |st| st.house.name == "Blue"}.count
  end

  def green_count
    students.select{ |st| st.house.name == "Green"}.count
  end


end

app/controllers/api/v1/sections_controller.rb
module Api
  module V1
    class SectionsController < ApplicationController

      before_action :fetch_klass

      before_action :fetch_section, only: [:show, :update, :destroy]

      def index
        @sections = @klass.sections
      end

      def show
      end

      def create
        @section = @klass.sections.new
        @section.name = params[:name]
        if @section.save
          head :created, location: api_v1_klass_sections_url(@klass)
        else
          head :bad_request
        end
      end

      def update
        @section.name = params[:name]
        if @section.save
          head :ok, location: api_v1_klass_section_url(@klass, @section)
        else
          head :bad_request
        end
      end

      def destroy
        if params[:name] == @section.name
          @section.destroy
          head :ok
        else
          head :bad_request
        end
      end

    private
      def fetch_klass
        @klass = Klass.find(params[:klass_id])
      end

      def fetch_section
        @section = @klass.sections.find(params[:id])
      end
    end
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

  before_action :fetch_klass

  def index
    # @sections = @klass.sections.all
    @sections = @klass.sections.includes(students: [:house])
    # is same as abv
  end

  def new
    @section = @klass.sections.new
  end

  def create
    @section = @klass.sections.new
    @section.name = params[:section][:name]
    @save_success = @section.save
  end

private
  def fetch_klass
    @klass = Klass.find(params[:klass_id])
  end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%# Section Creation Modal  %>
<div class="modal fade" id="new_section" tabindex="-1" role="dialog" aria-labelledby="newSection">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add a new Section</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@klass, @section], remote: true, html: { id: "new-section-form"} do |f| %>
          <%= f.input :name %>
          <%= f.submit "Add Section", class:"btn btn-primary"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/sections/_section.html.erb
<%= link_to(klass_section_students_path(@klass, section),
            class: "list-group-item section-item",
            id: dom_id(section), data: {toggle: "tooltip", placement: "right" }, title: "click for Students list!",
            remote: true) do
              raw(section.name) +
              house_counts_tag(section.houses_count)
            end
%>

app/views/sections/create.js.erb
$('#new_section').modal('hide')
<% if @save_success %>
  $("#sections-list").append("<%= j render(@section) %>");

  $("form#new-section-form")[0].reset();
  // reset is defined on dom ele but not on jquery so [0] is added
<% end %>


// for here it goes to index of section

app/views/sections/index.js.erb
StudentDBUtils.show("#sections");
$("#sections-list").html('<%= j render(@sections) %>');
$("#sections .panel-heading a").attr('href', '<%= new_klass_section_path(@klass) %>');
StudentDBUtils.hide("#students");
StudentDBUtils.hide("#student-details");
$("a.klass-item").removeClass("active");
$("a#<%= dom_id(@klass) %>").addClass("active");

app/views/sections/new.js.erb
$("#new_section").remove();
$("body").append("<%= j render(partial: "sections/form") %>")
$('#new_section').modal('show')