config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :klasses, except: [:edit, :new] do
        resources :sections, except: [:edit, :new] do
          resources :students, except: [:edit, :new]
        end
      end
    end
    namespace :v2 do
      resources :klasses, except: [:edit, :new]
    end
    namespace :v3 do
      resources :klasses, except: [:edit, :new]
    end
  end

  resources :klasses do
    resources :sections do
      resources  :students
      resources  :attendance_registries
    end
  end

  resources :exams, only: [:index, :new, :create]

  root 'klasses#index'

end

app/controllers/api/v1/klasses_controller.rb
module Api
  module V1
    class KlassesController < ApplicationController
      before_action :fetch_klass, only: [:show, :update, :destroy]

      def index
        @klasses = Klass.all
      end

      def show
      end

      def create
        @klass = Klass.new
        @klass.name = params[:name]
        if @klass.save
          head :created, location: api_v1_klass_url(@klass)
        else
          head :bad_request
        end
      end

      def update
        @klass.name = params[:name]
        if @klass.save
          head :ok, location: api_v1_klass_url(@klass)
        else
          head :bad_request
        end
      end

      def destroy
        if params[:name] == @klass.name
          @klass.destroy
          head :ok
        else
          head :bad_request
        end
      end

    private
      def fetch_klass
        @klass = Klass.find(params[:id])
      end
    end
  end
end

app/controllers/api/v2/klasses_controller.rb
module Api
  module V2
    class KlassesController < ApplicationController
      before_action :fetch_klass, only: [:show, :update, :destroy]

      def index
        @klasses = Klass.all
      end

      def show
      end

      def create
        @klass = Klass.new
        @klass.name = params[:name]
        if @klass.save
          head :created, location: api_klass_url(@klass)
        else
          head :bad_request
        end
      end

      def update
        @klass.name = params[:name]
        if @klass.save
          head :ok, location: api_klass_url(@klass)
        else
          head :bad_request
        end
      end

      def destroy
        if params[:name] == @klass.name
          @klass.destroy
          head :ok
        else
          head :bad_request
        end
      end

    private
      def fetch_klass
        @klass = Klass.find(params[:id])
      end
    end
  end
end

app/controllers/api/v3/klasses_controller.rb
module Api
  module V3
    class KlassesController < ApplicationController
      before_action :fetch_klass, only: [:show, :update, :destroy]

      def index
        @klasses = Klass.all
      end

      def show
      end

      def create
        @klass = Klass.new
        @klass.name = params[:name]
        if @klass.save
          head :created, location: api_klass_url(@klass)
        else
          head :bad_request
        end
      end

      def update
        @klass.name = params[:name]
        if @klass.save
          head :ok, location: api_klass_url(@klass)
        else
          head :bad_request
        end
      end

      def destroy
        if params[:name] == @klass.name
          @klass.destroy
          head :ok
        else
          head :bad_request
        end
      end

    private
      def fetch_klass
        @klass = Klass.find(params[:id])
      end
    end
  end
end

app/controllers/klasses_controller.rb
class KlassesController < ApplicationController

  def index
    @klasses = Klass.all.includes(students: [:house])

    @new_klass = Klass.new
  end

  def create
    @klass = Klass.new
    @klass.name = params[:klass][:name]

    @save_success = @klass.save # .save returns true or false
    if @klass.save
    else
    end
  end
end

app/helpers/klasses_helper.rb
module KlassesHelper
end

app/views/klasses/_form.html.erb
<%# Class Creation Modal  %>
<div class="modal fade" id="new_klass" tabindex="-1" role="dialog" aria-labelledby="newKlass">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add a new Class</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for @new_klass, remote: true, html: { id: "new-klass-form"} do |f| %>
          <%= f.input :name %>
          <%= f.submit "Add Class", class:"btn btn-primary"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/klasses/_klass.html.erb
<%= link_to(klass_sections_path(klass),
            id: dom_id(klass),
            class: "list-group-item klass-item", data: {toggle: "tooltip", placement: "right" }, title: "click for sections list!",
            remote: true) do
              raw(klass.name +
              house_counts_tag(klass.houses_count))
            end
%>

app/views/klasses/create.js.erb
$('#new_klass').modal('hide')
<% if @save_success %>
  $("#klasses-list").append("<%= j render(@klass) %>");

  $("form#new-klass-form")[0].reset();
  // reset is defined on dom ele but not on jquery so [0] is added
<% end %>

app/views/klasses/index.html.erb
<div id="school-board" class="container-fluid">
  <h1>School <%= link_to "Upload Marks List", new_exam_path ,id: "upload-marks-trigger", class: "pull-right btn btn-primary" %> </h1>

  <div class="row">
    <div id="klasses" class="col-md-2">
      <div class="panel panel-info">
        <div class="panel-heading">
          <b>Classes</b>
          <a type="button" href="#" class="pull-right" data-toggle="modal" data-target="#new_klass">
            <%= fa_icon "plus-square" %>
          </a>
        </div>
        <div id="klasses-list" class="list-group">
            <%= render @klasses  %>
             <!-- refers to @klasses in index action and partial _klass.html.erb by convection -->
            <%# render partial: 'klasses/klass', locals: {klass: @klasses}  %>
            <!-- by configuration -->
          </div>
      </div>
    </div>

    <div id="sections" class="col-md-2 hidden">
      <div class="panel panel-info">
        <div class="panel-heading">
          <b>Sections</b>
          <!-- <a type="button" href="#" class="pull-right">
            <%= fa_icon "plus-square" %>
          </a> -->
          <%= link_to fa_icon("plus-square"), "#", class: "pull-right", remote:  true %>
        </div>
        <div id="sections-list" class="list-group">

        </div>
      </div>
    </div>

    <div id="students" class="col-md-4 hidden">
      <div class="panel panel-info">
        <div class="panel-heading">
          <b>Students</b>
          <%= link_to fa_icon("plus-square"), "#", id: "add-student-trigger", class: "pull-right", remote:  true %>
          <span class= "pull-right">&nbsp; &nbsp;</span>
          <%= link_to fa_icon("hand-o-up"), "#",id: "take-attendence-trigger", class: "pull-right", remote:  true %>
        </div>
        <div id="students-list" class="list-group">

        </div>
      </div>
    </div>

    <div id="attendance" class="col-md-4 hidden">
      <div class="panel panel-info">
        <div class="panel-heading">
          <b>Attendance</b>
          <%= link_to "Submit", "#",id: "submit-attendance", class: "btn btn-sm btn-primary pull-right", remote:  true %>
          <span class= "pull-right btn btn-sm">&nbsp; or &nbsp;</span>
          <%= link_to "Cancel", "#", id: "cancel-attendance", class: "btn btn-sm btn-default pull-right", remote:  true %>
        </div>
        <div id="attentants-list" class="list-group">

        </div>
      </div>
    </div>

    <div id="student-details" class="col-md-4 hidden">
      <div class="panel panel-info">
        <div class="panel-heading">
          <b>Student Details</b>
          <%= link_to fa_icon("pencil-square-o"), "#", class: "pull-right", remote:  true %>
        </div>
        <div class="panel-body">
          Panel content
        </div>
      </div>
    </div>

  </div>
</div>


<%= render partial: 'klasses/form' %>